import Home from "./Home";
import MarketPlace from "./MarktetPlace";
import EcoSystem from "./EcoSystem";
import RoadMap from "./RoadMap";
import MagicNFT from "./MagicNFT";
import Socialize2Earn from "./Socialize2Earn";
import OurTeam from "./OurTeam";
import PersonalAccount from "./PersonalAccount";
import Register from "./Register";
export { Home, MarketPlace, EcoSystem, RoadMap, MagicNFT, Socialize2Earn, OurTeam, PersonalAccount ,Register};
